export type { Diff, DiffKind } from './core/diff'
export { diff } from './core/diff'
export { diffmerge } from './core/diffmerge'
export { redo } from './core/redo'
export { undo } from './core/undo'
